#!/bin/bash -e
. /etc/sentry-usbkey/config
error() { echo "$0: error: $2" >&2; exit $1; }
[[ "$(id -u)" != "0" ]] && error 1 "must be run as root"
[[ $1 == '-h' ]] && help=yes && shift
if [[ $help || $# != 2 ]]; then
  echo "Usage: $0 <username> <keyfile>" >&2
  exit 0
fi
username=$1
keypath=$2
[[ ! -r "$keypath" ]] && error 2 "$keypath is unreadable"
dev=/dev/block/$(udevadm info --device-id-of-file="$keypath")
info=$(udevadm info --path="$dev" | cut -c4- | sed 's/=/ /')
while read -a field; do
  [[ "${field[0]}" == "ID_PART_ENTRY_NUMBER" ]] && ID_PART_ENTRY_NUMBER=${field[1]}
  [[ "${field[0]}" == "ID_SERIAL" ]] && ID_SERIAL=${field[1]}
done <<< "$info"
[[ -z "$ID_PART_ENTRY_NUMBER" || -z "$ID_SERIAL" ]] && error 3 "cannot use device $dev to hold a key"
keypath_cannon=$(readlink -e "$keypath")
keypath_mountpoint=$(stat --format="%m" "$keypath_cannon")
keypath_relative=${keypath_cannon:${#keypath_mountpoint}}
[[ ! -r $keypath_mountpoint$keypath_relative ]] && error 4 "could not determine relative path of key on device"
check=$(grep -m 1 "^$ID_SERIAL " "$KEYS" 2>/dev/null || true)
[[ -n "$check" ]] && error 5 "this key device already used by ${check##* }"
echo "$ID_SERIAL $ID_PART_ENTRY_NUMBER $keypath_relative $username" >> "$KEYS"
echo "Entry added for $username"
