#!/bin/bash -e
[[ "$(id -u)" != "0" ]] && echo "Must be run as root" >&2 && exit 1
[[ -z "$ID_SERIAL" || -z "$ID_PART_ENTRY_NUMBER" || -z "$ID_FS_UUID" || -z "$DEVNAME" ]] && exit
. /etc/sentry-usbkey/config
mkdir -p "$LOGDIR"
LOG=$LOGDIR/access.log
[[ -n "$DRYRUN" ]] && socat() { echo "socat $@"; cat; } && LOG=/dev/stderr
log() { echo "$(date -R) $DEVNAME $@" >> $LOG; }
devid=$(echo "$ID_SERIAL$ID_PART_ENTRY_NUMBER$ID_FS_UUID$ID_FS_LABEL" | sha224sum); devid=${devid%% *}
keys=$(<"$KEYS")
while read -a field; do
  [[ "${field[0]::1}" == '#' ]] && continue
  if [[ "${field[0]}" == "$devid" ]]; then
    path=${field[1]}
    user=${field[2]}
  fi
done <<< "$keys"
if [[ -n "$path" && -n "$user" ]]; then
  mp=$(mktemp -d)
  mount -o ro "$DEVNAME" "$mp"
  key="$mp/$path"
  if [[ -r "$key" ]]; then
    secret=$(sha512sum "$key"); secret=${secret%% *}
    secret=$(echo "$secret$devid$path" | sha512sum); secret=${secret%% *}
  else
    log "Could not find keyfile on key registered for user $user"
  fi
  umount "$mp"
  rmdir "$mp"
  if [[ -n "$secret" ]]; then
    mksentrycommand() {
      json_line() { echo '{}' | jshon "$@" | tr -d '\t\n'; echo; }
      json_line -s auth -i action -s "$user" -i user -s "$secret" -i secret
      json_line -s unlock -i action
    }
    mksentrycommand | socat stdin ssl:$SENTRY_HOST:$SENTRY_PORT,cafile="$SENTRY_CERT",cert="$CERT",key="$PRIVKEY" |& while read -r line; do log "$line"; done
    log "Sent unlock command for user $user"
  fi
elif [[ -z "$partition" ]]; then
  log "Disk not recognized as a key; trying requests"
  sentry-usbkey-reqtry "$DEVNAME" |& while read -r line; do log "$line"; done
  if ! (echo "$keys" | diff - "$KEYS" >&/dev/null); then
    log "Keys file changed; trying again"
    exec "$0"
  fi
fi
